source=$HOME/.cache/wal/colors-hyprland.conf
source=./hyprland/monitor.conf
source=./hyprland/envs.conf
source=./hyprland/input.conf
source=./hyprland/autoexec.conf
source=./hyprland/appearance.conf
source=./hyprland/binds.conf
source=./hyprland/rules.conf
#source=./plugins/hycov.conf
#source=./nvidia.conf


##     __  ____
##    /  |/  (_)__ ____
##   / /|_/ / (_-</ __/
##  /_/  /_/_/___/\__/
##

dwindle {
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc { 
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    enable_anr_dialog = false
}

debug {
    overlay = false
    suppress_errors = false
    disable_logs = false
}
