preload = /home/bl00d/Pictures/wallpapers/wallhaven-we97wq.jpg
wallpaper = /home/bl00d/Pictures/wallpapers/wallhaven-we97wq.jpg
#preload = /home/bl00d/Pictures/wallpapers/minimal-landscape-wallpapers.png
#wallpaper = ,/home/bl00d/Pictures/wallpapers/minimal-landscape-wallpapers.png
