
##     __  _______  _  ________________  ___  ____
##    /  |/  / __ \/ |/ /  _/_  __/ __ \/ _ \/ __/
##   / /|_/ / /_/ /    // /  / / / /_/ / , _/\ \  
##  /_/  /_/\____/_/|_/___/ /_/  \____/_/|_/___/  
##

monitor=,preferred,auto,1
#monitor=eDP-1, disabled
monitor=HDMI-A-1, 1366x768@60, auto, 1
#monitor=HDMI-A-1, preferred, 1366x0, 1
debug:disable_scale_checks=true

$firstMonitor = LVDS-1
##HDMI-A-1
$secondMonitor = LVDS-1


workspace = 1, monitor:$firstMonitor, default:true
workspace = 2, monitor:$firstMonitor
workspace = 3, monitor:$firstMonitor
workspace = 4, monitor:$firstMonitor
workspace = 5, monitor:$firstMonitor
workspace = 6, monitor:$secondMonitor
workspace = 7, monitor:$secondMonitor
workspace = 8, monitor:$secondMonitor
workspace = 9, monitor:$secondMonitor
workspace = 0, monitor:$secondMonitor

#workspace = 1, monitor:$firstMonitor
#workspace = 2, monitor:$firstMonitor
#workspace = 3, monitor:$firstMonitor
#workspace = 4, monitor:$firstMonitor
#workspace = 5, monitor:$firstMonitor
#workspace = 6, monitor:$secondMonitor
#workspace = 7, monitor:$secondMonitor
#workspace = 8, monitor:$secondMonitor
#workspace = 9, monitor:$secondMonitor
#workspace = 10, monitor:$secondMonitor
