##    _      _______  _____  ____ _      ______
##   | | /| / /  _/ |/ / _ \/ __ \ | /| / / __/
##   | |/ |/ // //    / // / /_/ / |/ |/ /\ \  
##   |__/|__/___/_/|_/____/\____/|__/|__/___/  
##                                           

windowrule = suppress_event maximize, match:class .*
windowrule = opacity 0.9 0.8, match:class seahorse|xdg-desktop-portal-gtk|vscodium
windowrule = float on, match:class xdg-desktop-portal-gtk|org.gnome.Nautilus|librewolf|xdg-desktop-portal-gtk4, match:title Folder Sharing|Library
windowrule = size 70% 70%, match:class xdg-desktop-portal-gtk
windowrule = opacity 0.99 override, match:class obsidian
windowrule = content 2, match:class mpv

windowrule = match:class obsidian|codium, opacity 0.99 override 0.99 override 1.0 override
windowrule = match:namespace ^(wofi|rofi)$, pin 1

layerrule = match:namespace ^(wofi|rofi|deluge)$, blur 1
layerrule = match:namespace ^(waybar)$, blur 0 ## Must not be activated unless the bar fills its area
